version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: docker build -t bbosajon/max-imagedocker .
      - run:
          name: Push Docker Image
          command: docker push bbosajon/max-imagedocker
      # Add any additional steps or commands as needed

workflows:
  my-workflow:
    jobs:
      - build