# Generated by Django 3.2.14 on 2023-07-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
