# Generated by Django 3.2.14 on 2023-07-09 09:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_auto_20230708_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Short Description'),
        ),
    ]
